[build]
  publish = "."
  
[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NODE_ENV = "production"

[dev]
  command = "npx serve ."
  port = 3000
  
# Netlify Forms
[form]
  path = "/"
  action = "/thank-you"
